CREATE TABLE TRABALHO(
    IDTRABALHO NUMBER NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    LUGAR VARCHAR2(255) NOT NULL,
    DIA VARCHAR2(255),
    HORA VARCHAR2(255)
);

ALTER TABLE TRABALHO ADD CONSTRAINT PK_IDTRABALHO PRIMARY KEY(idtrabalho);
CREATE SEQUENCE seq_trabalho INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 NOCACHE NOCYCLE;
SELECT * from trabalho;